### ISSUE TITLE
script should use rasa methods

### ISSUE THREAD

**Issue by amn41** [RasaHQ/NLU-training-data#17]
https://github.com/RasaHQ/NLU-training-data/blob/f99c3ad15df7bdd98788062f2ac4d36f5dac5175/how-to-remove-entities/entity-remove-script#L12

@JEM-Mosig (@EmmaWightman said you wrote this script, right?)

this should use `rasa` 's built in methods, rather than a regex. that way this also works for the `json` format, here's a rough example:

```
from rasa.nlu.training_data import load_data

data = load_data('test.md')

for e in data.training_examples:
    e.set("entities", [])

with open('no_entities.md', 'w') as f:
    f.write(data.nlu_as_markdown())
```

**Comment by EmmaWightman** [comment]
Thank you for taking a look at this @amn41

**Comment by JEM-Mosig** [comment]
@EmmaWightman I tried to create a Pull Request, but I cannot push the changes. Apparently I don't have the correct access rights:
```
ERROR: Permission to RasaHQ/NLU-training-data.git denied to JEM-Mosig.
fatal: Could not read from remote repository.
```

**Comment by EmmaWightman** [comment]
Since we resolved by adding @JEM-Mosig as a collaborator and refreshing the PR, will close this issue. Thank you for the support! :)
