### ISSUE TITLE
Retail

### ISSUE THREAD

**Issue by simplymanas** [RasaHQ/NLU-training-data#32]
### This category is for intents that can be used to train bots for retail domain, such as "where is my order"

List of intents in this category:

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by EmmaWightman** [comment]
Hi @simplymanas 

Looks good, thank you for submitting the PR :)
