### ISSUE TITLE
Would be nice to provide Basic NLU data in other languages too

### ISSUE THREAD

**Issue by iamtofr** [RasaHQ/NLU-training-data#40]
What about other languages? Is there a place to leave my german NLU data?

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
@EmmaWightman what do you think?
