### ISSUE TITLE
Education training Dataset

### ISSUE THREAD

**Issue by vishwasrawat** [RasaHQ/NLU-training-data#43]
It would be great to have a Training DataSet that aims to provide the name of different courses under the various streams (Area of Interest).

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
