### ISSUE TITLE
Restaurant table reservation training data

### ISSUE THREAD

**Issue by shrey1608** [RasaHQ/NLU-training-data#49]
I would like to contribute restaurant table reservation training data consisting of user location, restaurant type, table preference  and user review

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by shrey1608** [comment]
Solved in #48
