### ISSUE TITLE
Adding crypto_currency as intent to banking/nlu.md && fixing grammar errors in the banking/nlu.md file

### ISSUE THREAD

**Issue by congnguyendinh0** [RasaHQ/NLU-training-data#58]
I want to

- [ ] -add crypto_currency as intent to banking/nlu.md  
- [ ] -fix grammar errors in banking/nlu.md
- [ ] -add Vietnamese Dong as data for the currency intent in the banking/nlu.md

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
sounds great, we'll review your PR soon!
