### ISSUE TITLE
Music and coffee dataset

### ISSUE THREAD

**Issue by salmanhiro** [RasaHQ/NLU-training-data#60]
Hello! I think it is cool to contribute training data about music and coffee talks. I will return here for the PR soon!

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by EmmaWightman** [comment]
@salmanhiro that would be awesome, we look forward to the PR :)
