### ISSUE TITLE
Add more mood training data

### ISSUE THREAD

**Issue by saumitrasapre** [RasaHQ/NLU-training-data#61]
I'd like to contribute some more training data to the mood folder

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @m-vdb will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Sure good idea @saumitrasapre . I see you already submitted a PR [here](https://github.com/RasaHQ/NLU-training-data/pull/62), correct? In case you missed it, [here are some guideline on how to contribute](https://github.com/RasaHQ/NLU-training-data#to-contribute-via-pull-request-follow-these-steps). Thanks for your help 🙏🏻

**Comment by saumitrasapre** [comment]
Yes that is correct! Glad to contribute!
