### ISSUE TITLE
Right single quotation mark being used instead of apostrophe

### ISSUE THREAD

**Issue by happilyeverafter95** [RasaHQ/NLU-training-data#69]
Looking through the training data, I noticed that the right single quotation mark (U+2019) `’` is being used in several places instead of the apostrophe `'`, for instance:

```
    - I’d like to make a transfer
    - I’d like to send money
```

I imagine that this would have an effect on downstream ML processes as the apostrophe is more commonly recognized in this context. Happy to open a pull request if this is an issue.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Now that I think of it, technically if the single quotation mark occurs in real life then it also makes sense to keep in the training data. Just to play safe there, feel free to just add two examples with the apostrophe in this case.

**Comment by happilyeverafter95** [comment]
Makes sense, closing the issue
