### ISSUE TITLE
dead link in readme file

### ISSUE THREAD

**Issue by dingusagar** [RasaHQ/NLU-training-data#71]
the following link in readme does't take anywhere.

_To help you remove the annotated entities from your training data, you can run [this script.](https://github.com/RasaHQ/NLU-training-data/blob/main/entity-removal-script.py)_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Good catch! Will fix it right away.
